---
- name: "Banco Pichincha :: Reporte Sistema Operativo :: Definir valores de reporte - Hostname"
  ansible.builtin.set_fact:
    aix_hostname: "{{ ansible_hostname }}"

- name: "Banco Pichincha :: Reporte Sistema Operativo :: Verificar si archivo resolv.conf existe"
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: result_resolv

