- name: "Banco Pichincha ::: Remediación AIX - Remediacion nodos APP Fase 2 - Continuar parchado"
  hosts: all
  gather_facts: false
  order: sorted
  tasks:
  - name: "Banco Pichincha ::: Remediación AIX - Definir hechos "
        ansible.builtin.set_fact:
          aix_report_post_patch: "{{ ansible_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.hour  }}{{ ansible_date_time.minute }}{{ ansible_date_time.second  }}_{{ tower_job_id }}_POST.txt"
  
  - name: "Banco Pichincha ::: Remediación AIX - Tomar evidencias previas al parchado"
    ansible.builtin.include_tasks:
      file: generar_status_aix.yaml
    vars:
      aix_report_file: "{{ aix_report_post_patch }}"
      
  - name: "Banco Pichincha ::: Remediación AIX - Definir hechos para Paso 2 APP - Parte 1"
    ansible.builtin.set_stats:
      data:
        success_list: '{{ hostvars | dict2items | json_query(success_query) }}' 
      per_host: false
    vars:
      success_query: "[?value.job_success==`true`].key"
      
   - name: "Banco Pichincha ::: Remediación AIX - Comparar informacion de reportes pre y post patching "
        ansible.builtin.shell: >-
          diff {{ aix_report_pre_patch }}  {{ aix_report_post_patch }}
        args:
          chdir: "{{ aix_reports_path }}"
        register: registro_aix_comparar_reportes
        failed_when: registro_aix_comparar_reportes.rc > 1
        changed_when: registro_aix_comparar_reportes.rc == 1
    
    - name: "Banco Pichincha ::: Remediación AIX - Comparar informacion de reportes pre y post patching - Resultado"
        ansible.builtin.debug:
          msg: "{{ registro_aix_comparar_reportes.stdout_lines }}" 
